name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to DigitalOcean
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.DO_SERVER_IP }} << 'EOF'
          cd /root/dev/finished-games/finished-games-backend
          git pull origin main
          npm install --omit=dev
          pm2 restart finished-games-backend || pm2 start npm --name "finished-games-backend" -- run start
        EOF
